feat: add li to ul
tom106gunma/JavaScript-assignment pull request #1
Opened 2023-05-02 00:54 UTC by tom106gunma

# [DOM構築 1](https://github.com/kenmori/handsonFrontend/blob/master/work/markup/1.md#1%E3%81%93%E3%81%AEdom%E3%82%92html%E5%86%85%E3%81%AEul%E3%81%AE%E4%B8%AD%E3%81%AB%E5%B7%AE%E3%81%97%E8%BE%BC%E3%82%93%E3%81%A7%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84)
### 1.このDOMをhtml内のulの中に差し込んでください

```html
<li>これです</li>
```
## [stackblitz](https://stackblitz.com/edit/web-platform-krbnuv?embed=0&file=lesson01%2Findex.js,lesson01%2Findex.html&initialpath=lesson01/index.html)
## Concerns and areas to focus on
- What would be the best way to name variables and id names with a practical application in mind?

2023-05-02 04:00 UTC, groovywave requested changes

2023-05-02 04:01 UTC, groovywave commented on lesson01/index.html
> +    <script src="index.js"></script>
FYI: You can move script tag with defer in head tag.
https://qiita.com/phanect/items/82c85ea4b8f9c373d684

2023-05-02 04:07 UTC, groovywave requested changes
You should remove some unnecessary files.

2023-05-02 08:58 UTC, nakagawamai commented
> What would be the best way to name variables and id names with a practical application in mind?

You may have already read it, but I suggest you read the readable code.

Sometimes a variable name should be clear and sometimes it should be ambiguous, depending on where it is used. 
For those with a short life or narrow scope, a generic name is fine. 
For those with a long life or wide scope, a clear name (one that requires little thought and is easy to understand at a glance) is recommended.

2023-05-02 09:05 UTC, nakagawamai commented on lesson01/index.js
> +target.innerHTML = "<li>これです</li>";
Q
When you have more target elements, what variable names do you plan to give them?

2023-05-02 09:14 UTC, nakagawamai commented on lesson01/index.html
> +    <script src="index.js"></script>
IMO
If you are going to put a defer, I think the script tag should be loaded in the header.

2023-05-02 09:22 UTC, nakagawamai commented
MUST
The PR title is the same as the commit name. I have received a suggestion from Mr. Morita to change the PR message to match the PR content.
https://discord.com/channels/726252977928667179/925558872180146176/1086468055770595408
<img width="869" alt="スクリーンショット 2023-05-02 18 19 47" src="https://user-images.githubusercontent.com/99260576/235628764-83e3837b-0edf-49e9-aaa1-3fda33fdb2d3.png">

2023-05-02 12:41 UTC, tom106gunma commented on lesson01/index.html
> +<html lang="en">
> Please change from en to ja

I did not check enough.
Thanks for pointing that out.

2023-05-02 13:20 UTC, tom106gunma commented on lesson01/index.html
> +    <script src="index.js"></script>
@groovywave 
> FYI: You can move script tag with defer in head tag.
> https://qiita.com/phanect/items/82c85ea4b8f9c373d684
I didn't know defer.
Thank you I learned a lot.

@nakagawamai 
I have never used defer, so I honestly don't know...

But I looked it up,
I found that it is more efficient by loading JS in parallel with HTML loading.
[https://takayamato.com/defer_async/](https://takayamato.com/defer_async/)

So I felt that when using defer, it would be better to load it in the header as Mis. Nakagawa said.

2023-05-02 14:04 UTC, tom106gunma commented on lesson01/index.js
> +target.innerHTML = "<li>これです</li>";
@nakagawamai 
> When you have more target elements, what variable names do you plan to give them?

I gave it a name such as `menber-list` to show what the list stands for.
I was worried that the name "target" did not allow for the increasing number of patterns.

> Why use `let`?

We used `let` because we thought that when adding a `<li>`, as in this case, we might also remove it.
However, for that reason, I felt that `const` might be better since the `<ul>` would remain the same.

> Why use innerHTML?
> Since this assignment is to create a DOM, it may be better to create the `li` itself.

I used innerHTML because I thought it was easier to write.
I see.
I think again what is Dom.

2023-05-02 22:31 UTC, tom106gunma commented
@groovywave @nakagawamai 
Please check them when you have time. 
I have changed the MUST part as you advised.

2023-05-03 00:39 UTC, groovywave commented
![〇](https://user-images.githubusercontent.com/76876597/235813427-26c27ba3-bf8b-4e3f-9115-e2ccd3b7f3ef.jpg)

There seem to be a few unnecessary files.
Please check that_(._.)_

2023-05-03 01:08 UTC, groovywave commented
Please click trash-can  icon being right side on unnecessary files or please do git command.
https://izumii19.hatenablog.com/entry/2019/05/05/171046
![〇](https://user-images.githubusercontent.com/76876597/235815827-9873cd45-1da8-497b-aab8-3a125543cbc4.jpg)

2023-05-03 08:22 UTC, nakagawamai commented on lesson01/index.js
> +target.innerHTML = "<li>これです</li>";
お返事ありがとうございます。
> We used let because we thought that when adding a `<li>`, as in this case, we might also remove it.
However, for that reason, I felt that const might be better since the `<ul>` would remain the same.

日本語ですみません。
letは値の再代入が必要な場合に使う、という認識ですが、ご説明にある`li`が消えてしまうというのがちょっと理解できていないです。申し訳ありません。

再代入が必要でないのであれば、`const`で良いと思います！

2023-05-03 08:35 UTC, nakagawamai commented on lesson01/index.js
> +target.innerHTML = "<li>これです</li>";
MUST
If it is OK to use const, it is better to use const.
```suggestion
const target = document.getElementById("js-target");
target.innerHTML = "<li>これです</li>";
```

2023-05-03 13:20 UTC, tom106gunma commented on lesson01/index.js
> +target.innerHTML = "<li>これです</li>";
@nakagawamai 
> ご説明にあるliが消えてしまうというのがちょっと理解できていないです。申し訳ありません。

いえ、説明うまく出来ていなくすみません。
`li`を追加する場合、
todoリストのようなフォームで入力されたものを`li`で表示して、
それを変更したり削除することがあるな。
だけど、今回の`target`に指定しているのは`ul`でしたね...
というのを英語で表現したかったです。

2023-05-03 14:56 UTC, groovywave commented on lesson01/index.html
> +<html lang="en">
Thank you:)

2023-05-03 14:57 UTC, groovywave commented on lesson01/index.html
> +    <script src="index.js"></script>
Thank you:)

2023-05-04 04:50 UTC, tom106gunma commented on lesson01/index.js
> +target.innerHTML = "<li>これです</li>";
Thanks for pointing that out.

I fixed.
[a8f7eca](https://github.com/tom106gunma/JavaScript-assignment/pull/1/commits/a8f7ecad05c4c3f71cadaa4e0e695f60224ef7d6)

2023-05-04 05:46 UTC, nakagawamai approved these changes

2023-05-04 11:49 UTC, merged

2023-05-04 12:25 UTC, tom106gunma commented on lesson01/index.js
> +target.innerHTML = "<li>これです</li>";
@groovywave 

Sorry for the delay in commenting.
I'll keep this file since I have a new template and I've been practicing Git.

[https://discord.com/channels/726252977928667179/726310768215195698/1090615383196700702](https://discord.com/channels/726252977928667179/726310768215195698/1090615383196700702)